<a href="https://colab.research.google.com/github/GITVIDHUB-1010/Data-Science-Learning/blob/main/NUMPY_phase_1_foundation%2Ccreation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Basics - August 2026

In [ ]:
import numpy as np

###creating arrays from list

In [ ]:
arr_1d=np.array([[1,2,3,4,5]])
print("1D ARRAY: ",arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D ARRAY:", arr_2d)

1D ARRAY:  [[1 2 3 4 5]]
2D ARRAY: [[1 2 3]
 [4 5 6]]


###list vs numpy array

In [ ]:
py_list = [1,2,3]
print("list multiplication",py_list *3)

arr= np.array([1,2,3,4,5]) #element wise multiplication
print("array multiplication", arr**2)

import time
start = time.time()
py_list = [i*2 for i in range(10000)]
print("list operation", time.time()-start)

start = time.time()
arr= np.arange(10000)*2
print("arrays operation",time.time()-start)


list multiplication [1, 2, 3, 1, 2, 3, 1, 2, 3]
array multiplication [ 1  4  9 16 25]
list operation 0.000865936279296875
arrays operation 0.0002639293670654297


###creating arrays from scratch

In [ ]:
zeros=np.zeros((3,4))
print("zeros array:\n",zeros)

ones=np.ones((3,4))
print("ones array:\n",ones)

full=np.full((3,3),5)
print("5 array full: \n",full)

random=np.random.random((2,3))
print("random: \n",random)

sequence = np.arange(0,11,1)
print('sequence range: \n',sequence)


zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
5 array full: 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
random: 
 [[0.45115702 0.53524408 0.42858375]
 [0.90515292 0.60193892 0.37714024]]
sequence range: 
 [ 0  1  2  3  4  5  6  7  8  9 10]


##VECTOR, MATRIX AND TENSOR

In [ ]:
vector=np.array([1,2,3,4,5])
print("Vector:\n",vector)

matrix=np.array([[1,2,3],
                 [3,4,5],
                 [4,5,6]])
print("Matrix: \n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[4,5],[5,6]]])
print("Tensor:\n",tensor)

Vector:
 [1 2 3 4 5]
Matrix: 
 [[1 2 3]
 [3 4 5]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[4 5]
  [5 6]]]


###Array properties

In [ ]:
arr=np.array([[[1,2],[3,4]],
              [[4,5],[6,2]]])
print("shape: ",arr.shape)
print("dimensions: ",arr.ndim)
print("size: ",arr.size)
print("data type: ",arr.dtype)

shape:  (2, 2, 2)
dimensions:  3
size:  8
data type:  int64


###Array Reshaping

In [ ]:
arr = np.arange(20)
print("org array: ",arr)

res= arr.reshape((4,5))
print("reshaped array:\n ",res)

flat=res.flatten()
print("flattened array: \n",flat)

transp= res.T ##converting rows to column and columns to rows
print('transpose: \n',transp)

org array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
reshaped array:
  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
transpose: 
 [[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
