#Operations on numpy-phase 2 -august 2026

In [ ]:
import numpy as np

##operations on 1d array

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing: ", arr[2:8])
print("With step: ",arr[0:8:3])
print("negative indexing: ", arr[-2])

Basic slicing:  [3 4 5 6 7 8]
With step:  [1 4 7]
negative indexing:  8


##operations on 2d array

In [ ]:
arr2=np.array([[1,2,3], #0th row
               [4,5,6], #1st row
               [6,7,8]]) #2nd row
print("specific element: ",arr2[2,1])
print('entire row: ',arr2[2]) # to print any row
print('entire column: ',arr2[:,1]) # to print any column




specific element:  7
entire row:  [6 7 8]
entire column:  [2 5 7]


##sorting in arrays numpy

In [ ]:
unsort = np.array([1,5,3,8,6,9,0,0,6,5,4,2,8,4,1,6])
print("sorted: ",np.sort(unsort))

arr2= np.array([[9,10],
                [1,3],
                [2,7]])

print("sorted 2d array by column: \n", np.sort(arr2,axis=0)) #axis=0 → work DOWN the rows
print("sorted 2d array by row: \n", np.sort(arr2,axis=1)) #axis=1 → work ACROSS the columns

sorted:  [0 0 1 1 2 3 4 4 5 5 6 6 6 8 8 9]
sorted 2d array by column: 
 [[ 1  3]
 [ 2  7]
 [ 9 10]]
sorted 2d array by row: 
 [[ 9 10]
 [ 1  3]
 [ 2  7]]


##Filtering in array

In [ ]:
num = np.array([1,2,3,4,5,6,7,8,9,10]) # num
even_num= num[num %2==0]
odd_num= num[num%2==1]


print("even numbers: ",even_num)
print("odd numbers: ",odd_num)


even numbers:  [ 2  4  6  8 10]
odd numbers:  [1 3 5 7 9]


###filter with mask

In [ ]:
mask = num > 5
print("numbers greater than 5:", num[mask])

numbers greater than 5: [ 6  7  8  9 10]


###fancy indexing vs np.where()

In [ ]:
indices = [0,2,4,1,4]
print(num[indices])

where_res= np.where(num>5)
print(num[where_res])
print(where_res)

[1 3 5 2 5]
[ 6  7  8  9 10]
(array([5, 6, 7, 8, 9]),)


In [ ]:
condition_arr = np.where(num%2==1,"True","False") #np.where(condition, value_if_true, value_if_false)
print(condition_arr)

['True' 'False' 'True' 'False' 'True' 'False' 'True' 'False' 'True'
 'False']


##adding and removing DATA

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])

sum= arr1+arr2
add= np.concatenate((arr1,arr2))
print(add)
print(sum)

[1 2 3 4 5 5 6 7 8 9]
[ 6  8 10 12 14]


##Array compatibility

In [ ]:
arr1= np.array([1,2,3,4])
arr2= np.array([5,2,3,6])
arr3= np.array([4,5,9,10])
print("compatibility",arr1.shape == arr2.shape)

compatibility True


In [ ]:
org = np.array([[1,2,3,4],[4,5,6,7]])
newrow= np.array([[1,2,3,6]])

with_new_row = np.vstack((org,newrow)) # VSTACK adds only rows
newcol= np.array([[3],[5]])
withnewcol= np.hstack((org,newcol))
print("original array\n",org)
print("new colummn\n",withnewcol)
print("new row\n",with_new_row)

original array
 [[1 2 3 4]
 [4 5 6 7]]
new colummn
 [[1 2 3 4 3]
 [4 5 6 7 5]]
new row
 [[1 2 3 4]
 [4 5 6 7]
 [1 2 3 6]]


In [ ]:
#DELETE OPERATIONS

arr = np.array([1,2,3,4,5,6])
deleted= np.delete(arr,2)
print(deleted)
print("deleted element",arr[2])

[1 2 4 5 6]
deleted element 3
